include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - 'build/**'

  errors:
    missing_return: error
    dead_code: warning

  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Style
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - camel_case_types
    - constant_identifier_names
    - empty_catches
    - empty_statements
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_this
    - unused_imports
